version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mental-math-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mental-math-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
